use SMPROG
go

SELECT            
                         CC.COD_COTIZACION, 
						 REPLICATE('0', 8 - LEN(CC.NUM_COTIZACION)) + CAST(CC.NUM_COTIZACION AS VARCHAR) AS NUM_COTIZACION,
						 ISNULL(CC.COD_EQUIPO,0) AS COD_EQUIPO,
						 ISNULL(CC.NOM_EQUIPO,'') AS NOM_EQUIPO,
						 ISNULL(CC.COD_AREA,0) AS COD_AREA , 
						 ISNULL(CC.NOM_AREA,'') AS NOM_AREA , 
						 ISNULL(CC.COD_GRUPO,0) AS COD_GRUPO , 
                         ISNULL(CC.NOM_GRUPO,'') AS NOM_GRUPO,
						 ISNULL(CC.COD_SUBGRUPO,0) AS COD_SUBGRUPO, 
						 ISNULL(CC.NOM_SUBGRUPO,'') AS NOM_SUBGRUPO, 
						 ISNULL(CC.NOM_MODELO,'') AS NOM_MODELO, 
						 ISNULL(CC.NUM_ACTIVO_FIJO,'') AS NUM_ACTIVO_FIJO, 
						 ISNULL(CC.SERIE,'') AS SERIE, 
						 CONVERT(varchar, CC.FEC_CREA, 103) AS FEC_CCOTIZACION, 
						 CONVERT(varchar, CC.FECHA_LIMITE, 103) + ' ' + CONVERT(varchar, CC.FECHA_LIMITE, 108) AS FECHA_LIMITE, 
						 (CASE WHEN CC.ESTADO = 'N' AND CC.FECHA_LIMITE < dbo.FSM_DEVUELVE_FECHA_ACTUAL(GETDATE(), CC.COD_EMPRESA) 
                         THEN 'VENCIDA' WHEN CC.ESTADO = 'N' THEN 'POR COTIZAR' WHEN CC.ESTADO = 'C' THEN 'COTIZADO' WHEN CC.ESTADO = 'R' 
						 THEN 'CALIFICADO' WHEN CC.ESTADO = 'D' THEN 'DESCALIFICADO' WHEN CC.ESTADO = 'A' THEN
                         'APROBADO' WHEN CC.ESTADO = 'E' THEN 'ELIMINADO' WHEN CC.ESTADO = 'O' THEN 'ORDEN GENERADA' WHEN CC.ESTADO = 'F' 
						 THEN 'CIERRE DE OT' WHEN CC.ESTADO = 'I' THEN 'NO APROBADO' WHEN CC.ESTADO = 'S'
                         THEN 'SUGERIDO NIVEL 1' WHEN CC.ESTADO = 'X' THEN 'RECHAZADA' ELSE 'ESTADO DESCONOCIDO' END) AS ESTADO_COTIZACION, 
						 ISNULL(CD.COD_REPUESTO,0) AS COD_REPUESTO,
						 ISNULL(CD.COD_INVENTARIO,'') AS COD_INVENTARIO,
						 ISNULL(CD.NUM_PARTE,'') AS  NUM_PARTE,
						 REPLACE(CASE WHEN CC.REPUESTO = 1 THEN ISNULL(CD.REPUESTO,0) ELSE ISNULL(CD.DESC_SERVICIO,0) END ,'"','')  AS DESCRIPCION_ITEM,
						 REPLACE(CAST(ROUND(ISNULL(CD.CANTIDAD,0),6,1) AS CHAR),'.',',') AS CANTIDAD,
						 REPLACE(CAST(ROUND(ISNULL(CD.CANT_APROBADA,0),6,1) AS CHAR),'.',',') AS CANTIDAD_APROBADA, 
						 REPLACE(CAST(ROUND(ISNULL(CD.CANT_SUGERIDA,0),6,1) AS CHAR),'.',',')  AS CANTIDAD_SUGERIDA,
                         REPLACE(CAST(ROUND(ISNULL(CD.CANT_RECHAZADA,0),6,1) AS CHAR),'.',',')  AS CANTIDAD_RECHAZADA_N1, 
						 REPLACE(CAST(ROUND(ISNULL(CD.CANT_RECHAZADA_SUP,0),6,1) AS CHAR),'.',',') AS CANTIDAD_RECHAZADA_SUP,
						 REPLACE(CAST(ROUND(ISNULL(CD.CANT_ANULADA,0),6,1) AS CHAR),'.',',')  AS CANTIDAD_ANULADA,
						 ISNULL(CD.USR_RECHAZA,'') AS USUARIO_RECHAZA_N1, 
                         ISNULL(CD.USR_RECHAZA_SUP,'') AS USUARIO_RECHAZA_SUP,
						 ISNULL(CD.JUSTIFICACION_ANULA,'') AS JUSTIFICACION_ANULA,
						 ISNULL(CP.COD_PROVEEDOR,0) AS COD_PROVEEDOR,
						 ISNULL(CP.NOM_PROVEEDOR,'') AS NOM_PROVEEDOR,
						 REPLACE(CAST(ROUND(ISNULL(CPP.CANTIDAD,0),6,1) AS CHAR),'.',',') AS CANTIDAD_COTIZADA, 
						 REPLACE(CAST(ROUND(ISNULL(CPP.VALOR_UNIT,0),6,1) AS CHAR),'.',',') AS VALOR_UNITARIO, 
                         REPLACE(CAST(ROUND(ISNULL(CPP.DSCTO_PORCENTAJE,0),6,1) AS CHAR),'.',',') AS DSCTO_PORCENTAJE,
						 REPLACE(CAST(ROUND(ISNULL(CPP.DESCUENTO_VALOR,0),6,1) AS CHAR),'.',',') AS DESCUENTO_VALOR,
						 REPLACE(CAST(ROUND(ISNULL(CPP.IVA_PORCENT,0),6,1) AS CHAR),'.',',')  AS IVA_PORCENTAJE, 
						 REPLACE(CAST(ROUND(ISNULL(CPP.IVA_VALOR,0),6,1) AS CHAR),'.',',') AS IVA_VALOR,
						 REPLACE(CAST(ROUND(ISNULL(CPP.SUBTOTAL,0),6,1) AS CHAR),'.',',') AS SUBTOTAL,
						 REPLACE(CAST(ROUND(ISNULL(CPP.CANT_SUGERIDA,0),6,1) AS CHAR),'.',',') AS CANT_SUGERIDA_PROV, 
                         REPLACE(CAST(ROUND(ISNULL(CPP.CANT_APROBADA,0),6,1) AS CHAR),'.',',') AS CANT_APROBADA_PROV, 
						 REPLACE(CAST(ROUND(ISNULL(CPP.CANT_RECHAZADA,0),6,1) AS CHAR),'.',',') AS CANT_RECHAZADA_N1_PROV, 
						 REPLACE(CAST(ROUND(ISNULL(CPP.CANT_RECHAZADA_SUP,0),6,1) AS CHAR),'.',',') AS CANT_RECHAZADA_SUP_PROV, 
						 CONVERT(varchar, CPP.FEC_CALIFICA, 103) AS FECHA_CALIFICA_PROV, 
						 CONVERT(varchar, CPP.FEC_CREA, 103) AS FECHA_COTIZA, 
						 CASE WHEN ISNULL(CCP.CANTIDAD_GLOBAL_COTIZADA, 0) > 0 THEN 'SI' ELSE 'NO' END AS COTIZADO, 
                         CASE WHEN ISNULL(CCP.CANTIDAD_GLOBAL_COTIZADA, 0) = 0 THEN REPLACE(CAST(ROUND(ISNULL(CPP.CANTIDAD,0),6,1) AS CHAR),'.',',') 
						 WHEN CPP.CANTIDAD > ISNULL(CCP.CANTIDAD_GLOBAL_COTIZADA, 0) 
                         THEN REPLACE(CAST(ROUND(ISNULL(CPP.CANTIDAD,0) - ISNULL(CCP.CANTIDAD_GLOBAL_COTIZADA, 0),6,1) AS CHAR),'.',',') 
						 ELSE 0 END AS CANT_DISPONIBLE_ANULAR,
						 CASE WHEN CC.SERVICIO = 1 THEN REPLICATE('0', 8 - LEN(RS.NUM_REQUISICION)) 
                         + CAST(RS.NUM_REQUISICION AS VARCHAR) ELSE CAST((ISNULL(CDS.TIPO_PEDIDO, '') + CDS.COD_PEDIDO) AS varchar) END AS SOC, 
                         CASE WHEN CC.SERVICIO = 0 THEN CONVERT(varchar, OP.fecha_emision,103) ELSE CONVERT(varchar, RS.FEC_CREA,103) END AS FECHA_SOC,
						 CASE WHEN CC.SERVICIO = 0 THEN CONVERT(varchar, OP.FEC_AUTORIZA,103) ELSE CONVERT(varchar, RS.FEC_CREA,103) END AS FEC_AUTORIZA_SOC, 
                         ISNULL(B.NOMBRE,'') AS NOM_BODEGA, 
						 CASE WHEN (DBO.DATETIMETOISO(DBO.FSM_DEVUELVE_FECHA_ACTUAL(GETDATE(), CC.COD_EMPRESA)) > DBO.DATETIMETOISO(CC.FECHA_LIMITE)) AND 
                         CP.ESTADO = 'N' THEN 'VENCIDA' WHEN CP.ESTADO = 'N' THEN 'POR COTIZAR' WHEN CP.ESTADO = 'C' THEN 'COTIZADO' WHEN CP.ESTADO = 'R' THEN 'CALIFICADA' WHEN CP.ESTADO = 'A' THEN 'APROBADO' WHEN CP.ESTADO
                          = 'O' THEN 'ORDEN GENERADA' WHEN CP.ESTADO = 'F' THEN 'CIERRE DE OT' WHEN CP.ESTADO = 'I' THEN 'NO APROBADO' WHEN CP.ESTADO = 'E' THEN 'ANULADA' WHEN CP.ESTADO = 'D' THEN 'DESCALIFICADO' WHEN CP.ESTADO
                          = 'F' THEN 'FINALIZADO' WHEN CP.ESTADO = 'X' THEN 'RECHAZADO' WHEN CP.ESTADO = 'S' THEN 'EN REVISION' ELSE 'ESTADO DESCONOCIDO' END AS ESTADO_COT_PROVEEDOR, 
                         CASE WHEN CPP.ESTADO = 'A' THEN 'COTIZADO' WHEN CPP.ESTADO = 'R' THEN 'CALIFICADA' WHEN CPP.ESTADO = 'P' THEN 'APROBADO' WHEN CPP.ESTADO = 'E' THEN 'ANULADA' WHEN CPP.ESTADO = 'D' THEN 'DESCALIFICADO'
                         WHEN CPP.ESTADO = 'X' THEN 'RECHAZADO' WHEN CPP.ESTADO = 'S' THEN 'EN REVISION' ELSE 'ESTADO DESCONOCIDO' END AS ESTADO_ITEM_COT_PROV, 
                         CASE WHEN CPP.CUMPLE_REQUISITO = 'S' THEN 'SI' ELSE 'NO' END AS CUMPLE_REQUISITO,
						 ISNULL(CC.COD_OT,0) as COD_OT, 
						 ISNULL(OTC.NUM_OT,0) as NUM_OT, 
						 (CASE WHEN OTC.ESTADO = 'A' AND ((OTC.FINALIZADA IS NULL OR OTC.FINALIZADA = '') AND OTC.FEC_FINALIZA IS NULL)
						 THEN 'ABIERTA' WHEN OTC.ESTADO = 'A' AND (OTC.FINALIZADA = 'S' OR OTC.FEC_FINALIZA IS NOT NULL) 
						 THEN 'FINALIZADA' WHEN OTC.ESTADO = 'R' THEN 'RE-ABIERTA' WHEN OTC.ESTADO = 'C' THEN 'CERRADA' WHEN OTC.ESTADO = 'E' 
						 THEN 'ANULADA' WHEN ISNULL(OTC.ESTADO,0)=0 THEN '' END) AS ESTADO_OT, 
                         ISNULL(CC.COD_EMPRESA,0) as COD_EMPRESA, 
						 ISNULL(OC.cod_compra,'') as cod_compra, 
						 CONVERT(varchar, OC.f_creacion,103) AS FEC_COMPRA, 
						 CASE OC.estado WHEN 'A' THEN 'ANULADA' WHEN 'C' THEN 'ABIERTA' WHEN 'F' THEN 'FINALIZADA' END AS ESTADO_COMPRA, 
                         REPLACE(CAST(ROUND(ISNULL(DC.cantidad,0) - ISNULL(DC.cant_anulada, 0),6,1) AS CHAR),'.',',') AS CANTIDAD_COMPRA
						 
						 ,
						 COALESCE((select top 1 cf.NUM_FACTURA from BOD_CAB_FACT_INGRESO cf where cf.COD_COMPRA = OC.cod_compra and cf.TIPO_OC = OC.TIPO_OC AND CF.ESTADO NOT IN('A') and cf.COD_EMPRESA = DC.COD_EMPRESA),'') NUMERO_FACTURA,
						 --ISNULL(cf.NUM_FACTURA,'') NUMERO_FACTURA,
						 ISNULL(D.guia_remision,'')  NUMERO_GUIA_IZ,
						 case when cc.SERVICIO = 1 then COALESCE(CONVERT(varchar, OTC.FEC_FINALIZA,103),'') else '' end FECHA_RECEPCION_SERVICIO,
						 case when cc.REPUESTO = 1 then COALESCE(CONVERT(varchar, d.Fecha_Documento,103),'') else '' end FECHA_RECEPCION_REPUESTO,
						 COALESCE(DATEDIFF(day, (CASE WHEN CC.SERVICIO = 0 THEN OP.fecha_emision ELSE Rs.FEC_CREA END),(CASE WHEN CC.SERVICIO = 0 THEN d.Fecha_Documento ELSE OTC.FEC_FINALIZA END) ),'') TIEMPO_ENTREGA_REPUESTO_SERVICIO

FROM                     dbo.TSM_COTIZACION_CAB AS CC INNER JOIN
                         dbo.TSM_COTIZACION_DET AS CD ON CD.COD_COTIZACION = CC.COD_COTIZACION LEFT OUTER JOIN
                         dbo.TSM_COTIZACION_DET_SOC AS CDS ON CDS.COD_COTIZACION = CD.COD_COTIZACION AND CDS.COD_REPUESTO = CD.COD_REPUESTO AND CDS.COD_ITEM = CD.COD_ITEM LEFT OUTER JOIN
                         dbo.TSM_COTIZACION_PROVEEDOR AS CP ON CP.COD_COTIZACION = CC.COD_COTIZACION LEFT OUTER JOIN
                         dbo.TSM_COTIZACION_PROV_PLANT AS CPP ON CPP.COD_COTIZACION_PROVEEDOR = CP.COD_COTIZACION_PROVEEDOR AND CPP.COD_REPUESTO = CD.COD_REPUESTO LEFT OUTER JOIN
                             (SELECT        CPS.COD_COTIZACION, CPPS.COD_REPUESTO, SUM(CPPS.CANTIDAD) AS CANTIDAD_GLOBAL_COTIZADA
                               FROM            dbo.TSM_COTIZACION_PROVEEDOR AS CPS LEFT OUTER JOIN
                                                         dbo.TSM_COTIZACION_PROV_PLANT AS CPPS ON CPPS.COD_COTIZACION_PROVEEDOR = CPS.COD_COTIZACION_PROVEEDOR
                               WHERE        (CPPS.ESTADO NOT IN ('E'))
                               GROUP BY CPS.COD_COTIZACION, CPPS.COD_REPUESTO) AS CCP ON CCP.COD_COTIZACION = CC.COD_COTIZACION AND CD.COD_REPUESTO = CCP.COD_REPUESTO LEFT OUTER JOIN
                         dbo.BOD_BODEGA AS B ON iSNULL(B.COD_BODEGA,0) = ISNULL(CDS.COD_BODEGA,0) LEFT OUTER JOIN
                         dbo.TSM_OT_CAB AS OTC ON ISNULL(OTC.COD_OT,0) = ISNULL(CC.COD_OT,0) LEFT OUTER JOIN
                         dbo.BOD_DETALLE_COMPRA AS DC ON DC.COD_COTIZACION = CC.COD_COTIZACION AND DC.COD_EMPRESA = CC.COD_EMPRESA AND DC.COD_REPUESTO_SOC = CD.COD_REPUESTO AND 
                         ISNULL(DC.cod_bodega,0) = ISNULL(CDS.COD_BODEGA,0) AND DC.cod_pedido = CDS.COD_PEDIDO AND DC.tipo_pedido = ISNULL(CDS.TIPO_PEDIDO,'') 
						 LEFT OUTER JOIN dbo.BOD_ORDEN_COMPRA AS OC ON OC.cod_compra = DC.cod_compra AND OC.COD_EMPRESA = DC.COD_EMPRESA AND OC.cod_proveedor = CP.COD_PROVEEDOR 
						 LEFT OUTER JOIN dbo.BOD_ORDEN_PEDIDO AS OP ON ISNULL(OP.cod_bodega,0) = ISNULL(CDS.COD_BODEGA,0) AND OP.cod_pedido = CDS.COD_PEDIDO AND OP.tipo_pedido = CDS.TIPO_PEDIDO
						 LEFT OUTER JOIN dbo.TSM_REQ_SERVICIO_CAB AS RS ON ISNULL(RS.COD_REQUISICION,0) = ISNULL(CDS.COD_REQUISICION,0) AND CASE WHEN CC.SERVICIO = 1 THEN 1 ELSE 0 END = 1
						 ----dbo.BOD_BODEGA AS B ON B.COD_BODEGA = CDS.COD_BODEGA LEFT OUTER JOIN
       ----                  dbo.TSM_OT_CAB AS OTC ON OTC.COD_OT = CC.COD_OT LEFT OUTER JOIN
       ----                  dbo.BOD_DETALLE_COMPRA AS DC ON DC.COD_COTIZACION = CC.COD_COTIZACION AND DC.COD_EMPRESA = CC.COD_EMPRESA AND DC.COD_REPUESTO_SOC = CD.COD_REPUESTO AND 
       ----                  DC.cod_bodega = CDS.COD_BODEGA  AND DC.cod_pedido = CDS.COD_PEDIDO AND DC.tipo_pedido = CDS.TIPO_PEDIDO  LEFT OUTER JOIN
       ----                  dbo.BOD_ORDEN_COMPRA AS OC ON OC.cod_compra = DC.cod_compra AND OC.COD_EMPRESA = DC.COD_EMPRESA AND OC.cod_proveedor = CP.COD_PROVEEDOR LEFT OUTER JOIN
       ----                  dbo.BOD_ORDEN_PEDIDO AS OP ON OP.cod_bodega = CDS.COD_BODEGA  AND OP.cod_pedido = CDS.COD_PEDIDO AND OP.tipo_pedido = CDS.TIPO_PEDIDO LEFT OUTER JOIN
       ----                  dbo.TSM_REQ_SERVICIO_CAB AS RS ON RS.COD_REQUISICION = CDS.COD_REQUISICION AND CASE WHEN CC.SERVICIO = 1 THEN 1 ELSE 0 END = 1
						 LEFT OUTER JOIN TSM_REQUISICION_CAB TRC ON TRC.COD_REQUISICION=CDS.COD_REQUISICION AND CASE WHEN CC.REPUESTO = 1 THEN 1 ELSE 0 END = 1
						 --LEFT OUTER JOIN BOD_CAB_FACT_INGRESO cf on cf.COD_COMPRA = OC.cod_compra and cf.TIPO_OC = OC.TIPO_OC AND CF.ESTADO NOT IN('A') and cf.COD_EMPRESA = DC.COD_EMPRESA
						 --LEFT OUTER JOIN BOD_CAB_MOVIMIENTO D on  D.Segun_Documento=CASE WHEN CC.SERVICIO = 1 THEN REPLICATE('0', 8 - LEN(RS.NUM_REQUISICION)) 
                         --+ CAST(RS.NUM_REQUISICION AS VARCHAR)  ELSE CAST((ISNULL(CDS.TIPO_PEDIDO, '') + CDS.COD_PEDIDO) AS varchar) END
						 LEFT OUTER JOIN BOD_CAB_MOVIMIENTO D on D.Segun_Documento = CASE WHEN CC.SERVICIO = 1 THEN  CAST(RS.NUM_REQUISICION AS VARCHAR) ELSE  CAST(TRC.NUM_REQUISICION AS VARCHAR)  END and D.tipo_movimiento='I' --ESTA LINEA ES
						 --LEFT OUTER JOIN BOD_CAB_MOVIMIENTO D on  D.Segun_Documento=OC.cod_compra
--where  CAST (D.f_creacion AS DATE) >='2024-07-19' and D.tipo_movimiento='I'
where  CAST (OC.f_creacion AS DATE) between '2024-07-01' and '2024-08-01' --AND CF.ESTADO NOT IN('A') --and D.tipo_movimiento='I'
--and 
--cc.COD_EQUIPO = 5850


-- select * from BOD_CAB_MOVIMIENTO
-- where Segun_Documento = '27832'

--select top 100 * from TSM_REQ_SERVICIO_CAB
--WHERE NUM_REQUISICION = '00027832'

--select top 100 * from TSM_REQUISICION_CAB
--WHERE NUM_REQUISICION = '00027832'

--SELECT * FROM TSM_COTIZACION_DET_SOC
--WHERE COD_REQUISICION = 27832

--SELECT * FROM TSM_REQUISICION_CAB
--WHERE COD_REQUISICION = 27832

/*

 select * from BOD_CAB_FACT_INGRESO -- ESTA ORDEN DE COMPRA TIENE DOS INGRESOS DE BODEGA
 where COD_COMPRA in ('0012027','0012028') and TIPO_OC = 'R' AND ESTADO NOT IN('A')
 
 select * from BOD_CAB_FACT_INGRESO
 where COD_CAB_FACT_INGRESO in (14035,14036)

 select  * from TSM_COTIZACION_PROVEEDOR
 where COD_COMPRA = '0012027' 

 select  * from BOD_DETALLE_COMPRA
 where COD_COMPRA = '0012027' 

 select  TIPO_OC ,* from BOD_ORDEN_COMPRA
 where COD_COMPRA = '0012027' 

 select * from BOD_CAB_FACT_INGRESO
 where COD_COMPRA = '0012027' and TIPO_OC = 'R' AND ESTADO NOT IN('A')
 

 */
