USE IPSPCamaroneraProduccion
GO

IF NOT OBJECT_ID('tempdb..#TMP_AJUSTE_MASIVO') IS NULL  DROP TABLE #TMP_AJUSTE_MASIVO
GO 
CREATE TABLE #TMP_AJUSTE_MASIVO
(
    NUEVOZONA INT,
	ID_ZONA INT,
	COD_ZONA VARCHAR(10),
    ZONA VARCHAR(80),
	NUEVOCAMARONERA INT,
    ID_CAMARONERA INT,
	COD_CAMARONERA VARCHAR(10),
	CAMARONERA VARCHAR(80),
    ID_SECTOR INT,
	COD_SECTOR VARCHAR(10),
	SECTOR VARCHAR(80),
	CAMBIO INT,
	NUEVOMZONA INT,
	ID_MZONA INT,
	COD_MZONA VARCHAR(10),
    MEGAZONA VARCHAR(80),
);
SET NOCOUNT ON; 

BEGIN TRY 
------ MEGA ZONA PENINSULA FALTA ORGANICOCH Y ORGANICOP
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA,	COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',50,'00050','APENDICE',0,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',51,'00051','CAMARPASA',0,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',53,'00053','DPESCA',0,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',0,'00000','1B',2,1,0,'00','PENINSULA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOA',1,0,'00000','PAÑAMAOA',56,'00056','PSECTORI',1,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOA',1,0,'00000','PAÑAMAOA',57,'00057','PSECTORII',1,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOA',1,0,'00000','PAÑAMAOA',63,'00063','PSECTORVIII',1,1,0,'00','PENINSULA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',58,'00058','PSECTORIII',1,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',59,'00059','PSECTORIV',1,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',60,'00060','PSECTORV',1,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',61,'00061','PSECTORVI',1,1,0,'00','PENINSULA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',62,'00062','PSECTORVII',1,1,0,'00','PENINSULA');


-----MEGA ZONA OCEANIA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',71,'00071','ELSALVADOR',0,1,0,'00','OCEANIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',70,'00070','FAROI',0,1,0,'00','OCEANIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',72,'00072','FAROII',0,1,0,'00','OCEANIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',73,'00073','FAROIII',0,1,0,'00','OCEANIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',74,'00074','PANAMA',0,1,0,'00','OCEANIA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PLAYAS',1,0,'00000','PLAYAS',75,'00075','CABALAI',1,1,0,'00','OCEANIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','PLAYAS',1,0,'00000','PLAYAS',76,'00076','CABALAII',1,1,0,'00','OCEANIA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','SABANA',1,0,'00000','SABANA',68,'00068','JAMAICA',1,1,0,'00','OCEANIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','SABANA',1,0,'00000','SABANA',69,'00069','SINGAPUR',1,1,0,'00','OCEANIA');


-----MEGA ZONA MEDIA FALTA CORVINERO C -- CUBA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENA',1,0,'00000','BAJENA',24,'00024','ARGENTINA',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENA',1,0,'00000','BAJENA',25,'00025','CANADA',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENA',1,0,'00000','BAJENA',32,'00032','RUMANIA',1,1,0,'00','MEDIA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',26,'00026','ESPAÑA',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',27,'00027','KANSAS',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',28,'00028','MEXICOI',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',29,'00029','MEXICOII',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',30,'00030','MEXICOIII',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',31,'00031','MEXICOIV',1,1,0,'00','MEDIA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',45,'00045','HONDURASBAJO',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',44,'00044','HONDURASALTO',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',43,'00043','GUATEMALA',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',39,'00039','CAPULSA',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',42,'00042','FINLANDIA',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',40,'00040','COSTARICAI',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',41,'00041','COSTARICAII',1,1,0,'00','MEDIA');
	

    INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROB',1,0,'00000','CORVINEROB',48,'00048','EMIRATOS',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROB',1,0,'00000','CORVINEROB',47,'00047','DAKAR',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CORVINEROB',1,0,'00000','CORVINEROB',46,'00046','CHIPRE',1,1,0,'00','MEDIA');	

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,7,'07','DAULAR',1,0,'00000','DAULAR',38,'00038','TRINIDAD',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,7,'07','DAULAR',1,0,'00000','DAULAR',37,'00037','ARUBA',1,1,0,'00','MEDIA');
	
    INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',23,'00023','RUANDA',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',21,'00021','MARRUECOS',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',82,'00082','EGIPTO',1,1,0,'00','MEDIA');		
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',20,'00020','CAMERUN',1,1,0,'00','MEDIA');	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',22,'00022','PAKISTAN',1,1,0,'00','MEDIA');
	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',35,'00035','JAPON',1,1,0,'00','MEDIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',33,'00033','CHINA',1,1,0,'00','MEDIA');		
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',34,'00034','HONGKONG',1,1,0,'00','MEDIA');	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',77,'00077','VIETNAM',1,1,0,'00','MEDIA');	


	-----MEGA ZONA GOLFO
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','GOLFOA',1,0,'00000','GOLFOA',65,'00065','SUECIAI',1,1,0,'00','GOLFO');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','GOLFOA',1,0,'00000','GOLFOA',66,'00066','SUECIAII',1,1,0,'00','GOLFO');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','GOLFOA',1,0,'00000','GOLFOA',64,'00064','AUSTRALIA',1,1,0,'00','GOLFO');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','GOLFOB',1,0,'00000','GOLFOB',67,'00067','NUEVAZELANDA',1,1,0,'00','GOLFO');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','GOLFOB',1,0,'00000','GOLFOB',83,'00083','BORABORA',1,1,0,'00','GOLFO');


	-----MEGA ZONA TAURA FALTA TAURAA -- TAURAIII TILAPIA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAA',0,1,'00001','TAURAA',79,'00079','TAURAIII',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAA',0,1,'00001','TAURAA',2,'00002','NURACORP',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAA',0,1,'00001','TAURAA',78,'00078','GARITA',0,1,0,'00','TAURA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',9,'00009','TAURAIV',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',81,'00081','TAURAV',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',10,'00010','TAURAVI',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',80,'00080','HOLANDA',0,1,0,'00','TAURA');


	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',14,'00014','LALUZ',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',11,'00011','TAURAVII',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',12,'00012','TAURAVIII',0,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',13,'00013','TAURAIX',0,1,0,'00','TAURA');

	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAD',1,0,'00000','TAURAD',4,'00004','TAURAI',1,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAD',1,0,'00000','TAURAD',5,'00005','TAURAII',1,1,0,'00','TAURA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','TAURAD',1,0,'00000','TAURAD',3,'00003','PORTILLO',1,1,0,'00','TAURA');



		-----MEGA ZONA CALIFORNIA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (0,6,'06','CHURUTE',0,25,'00025','CHURUTE',36,'00036','CHURUTE',0,1,0,'00','CALIFORNIA');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CALIFORNIAA',1,0,'00000','CALIFORNIAA',49,'00049','LOSANGELES',1,1,0,'00','CALIFORNIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CALIFORNIAA',1,0,0,'CALIFORNIAA',15,'00015','SANTABARBARA',1,1,0,'00','CALIFORNIA');
	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',16,'00016','SANDIEGO',1,1,0,'00','CALIFORNIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',17,'00017','SANFRANCISCO',1,1,0,'00','CALIFORNIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',18,'00018','SANTAMONICA',1,1,0,'00','CALIFORNIA');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',19,'00019','SANTAROSA',1,1,0,'00','CALIFORNIA');

	-----megazona
	IF NOT EXISTS(SELECT * FROM parMegaZona WHERE nombre IN(SELECT MEGAZONA FROM #TMP_AJUSTE_MASIVO WHERE NUEVOMZONA=1))
	BEGIN
	     DECLARE @idMegaZona int 
		 DECLARE @idMaxMegaZona int 
		 SET @idMegaZona = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WHERE tabla='megaZona')
		 BEGIN
			SELECT TOP 1 @idMegaZona = ultimaSecuencia
				FROM parSecuencial WHERE tabla='megaZona'
		 END 
		  
		  INSERT INTO parMegaZona(idMegaZona, idDivision, codigo, nombre, descripcion, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion)
		  SELECT DISTINCT
		  @idMegaZona + ROW_NUMBER() OVER (ORDER BY MEGAZONA)
		  ,1
		  ,FORMAT(@idMegaZona + ROW_NUMBER() OVER (ORDER BY MEGAZONA), '00')
		  ,MEGAZONA
		  ,MEGAZONA
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE NUEVOMZONA=1
		  AND NOT EXISTS (SELECT * FROM parMegaZona WHERE nombre = MEGAZONA)
		  GROUP BY MEGAZONA

		  SELECT @idMaxMegaZona = MAX(idMegaZona) FROM parMegaZona
		  IF(@idMegaZona =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('megaZona',  @idMaxMegaZona)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMaxMegaZona WHERE tabla ='megaZona'
		  END

		  UPDATE x 
		  SET x.COD_MZONA= y.codigo,
		      x.ID_MZONA=y.idMegaZona
		  FROM #TMP_AJUSTE_MASIVO x,
		  parMegaZona y
		  WHERE y.nombre = x.MEGAZONA
		  AND x.NUEVOMZONA=1

	END
	ELSE
	BEGIN
	      UPDATE x 
		  SET x.COD_MZONA= y.codigo,
		      x.ID_MZONA=y.idMegaZona
		  FROM #TMP_AJUSTE_MASIVO x,
		  parMegaZona y
		  WHERE y.nombre = x.MEGAZONA
	END

	      UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parMegaZona x
		  WHERE  NOT EXISTS (SELECT * FROM #TMP_AJUSTE_MASIVO WHERE MEGAZONA = x.nombre)

	----zona
    IF NOT EXISTS(SELECT * FROM parZona WHERE nombre IN(SELECT ZONA FROM #TMP_AJUSTE_MASIVO WHERE NUEVOZONA=1))
	BEGIN
	     DECLARE @idZona INT 
		 DECLARE @idMaxZona INT 
		 SET @idZona = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WHERE tabla='Zona')
		 BEGIN
			SELECT TOP 1 @idZona = ultimaSecuencia
				FROM parSecuencial WHERE tabla='Zona'
		 END 
		  
		  INSERT INTO parZona(idZona, idMegaZona, idDivision, codigo, codigoSri ,nombre, descripcion, direccion, telefono, correoElectronico, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion, numeroPedidoLarva, aplicaApiLarvia)
		  SELECT DISTINCT
		  @idZona + ROW_NUMBER() OVER (ORDER BY ZONA)
		  ,ID_MZONA
		  ,1
		  ,FORMAT(@idZona + ROW_NUMBER() OVER (ORDER BY ZONA), '00')
		  ,FORMAT(@idZona + ROW_NUMBER() OVER (ORDER BY ZONA), '00')
		  ,ZONA
		  ,ZONA
		  ,''
		  ,''
		  ,''
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,0
		  ,0
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE NUEVOZONA=1
		  AND NOT EXISTS (SELECT * FROM parZona WHERE nombre = ZONA)
		  GROUP BY ZONA,ID_MZONA

		  SELECT @idMaxZona = MAX(idMegaZona) FROM parMegaZona
		  IF(@idZona =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('Zona',  @idMaxZona)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMaxZona WHERE tabla ='Zona'
		  END

		  UPDATE x 
		  SET x.COD_ZONA= y.codigo,
		      x.ID_ZONA=y.idZona
		  FROM #TMP_AJUSTE_MASIVO x,
		  parZona y
		  WHERE y.nombre = x.ZONA
		  AND x.NUEVOZONA=1

	END
	ELSE
	BEGIN
	      UPDATE x 
		  SET x.COD_ZONA= y.codigo,
		      x.ID_ZONA=y.idZona
		  FROM #TMP_AJUSTE_MASIVO x,
		  parZona y
		  WHERE y.nombre = x.ZONA
	END

		      UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parZona x
		  WHERE  NOT EXISTS (SELECT * FROM #TMP_AJUSTE_MASIVO WHERE ZONA = x.nombre)

		----camaronera
    IF NOT EXISTS(SELECT * FROM parCamaronera WHERE nombre IN(SELECT CAMARONERA FROM #TMP_AJUSTE_MASIVO WHERE NUEVOCAMARONERA=1))
	BEGIN
	     DECLARE @id INT 
		 DECLARE @idMax INT 
		 SET @id = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WHERE tabla='Camaronera')
		 BEGIN
			SELECT TOP 1 @id = ultimaSecuencia
				FROM parSecuencial WHERE tabla='Camaronera'
		 END 
		  
		  INSERT INTO parCamaronera(idCamaronera, idZona, codigo ,nombre, descripcion, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion)
		  SELECT DISTINCT
		   @id + ROW_NUMBER() OVER (ORDER BY CAMARONERA)
		  ,ID_ZONA
		  ,FORMAT(@id + ROW_NUMBER() OVER (ORDER BY CAMARONERA), '00000')
		  ,CAMARONERA
		  ,CAMARONERA
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE NUEVOCAMARONERA=1
		  AND NOT EXISTS (SELECT * FROM parCamaronera WHERE nombre = CAMARONERA)
		  GROUP BY CAMARONERA, ID_ZONA

		  SELECT @idMax = MAX(idCamaronera) FROM parCamaronera
		  IF(@id =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('Camaronera',  @idMax)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMax WHERE tabla ='Camaronera'
		  END

		  UPDATE x 
		  SET x.COD_CAMARONERA= y.codigo,
		      x.ID_CAMARONERA=y.idCamaronera
		  FROM #TMP_AJUSTE_MASIVO x,
		  parCamaronera y
		  WHERE y.nombre = x.CAMARONERA
		  AND x.NUEVOCAMARONERA=1

		  UPDATE x 
		  SET x.COD_CAMARONERA= y.codigo,
		      x.ID_CAMARONERA=y.idCamaronera
		  FROM #TMP_AJUSTE_MASIVO x,
		  parCamaronera y
		  WHERE y.nombre = x.CAMARONERA

	END
	ELSE
	BEGIN
	      UPDATE x 
		  SET x.COD_CAMARONERA= y.codigo,
		      x.ID_CAMARONERA=y.idCamaronera
		  FROM #TMP_AJUSTE_MASIVO x,
		  parCamaronera y
		  WHERE y.nombre = x.CAMARONERA
	END

		  UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parCamaronera x
		  WHERE  NOT EXISTS (SELECT * FROM #TMP_AJUSTE_MASIVO WHERE CAMARONERA = x.nombre)

			----sector
    IF NOT EXISTS(SELECT * FROM parSector WHERE nombre IN(SELECT SECTOR FROM #TMP_AJUSTE_MASIVO WHERE CAMBIO=2))
	BEGIN
	     DECLARE @ids INT 
		 DECLARE @idMaxs INT 
		 SET @ids = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WHERE tabla='Sector')
		 BEGIN
			SELECT TOP 1 @ids = ultimaSecuencia
				FROM parSecuencial WHERE tabla='Sector'
		 END 
		  
		  INSERT INTO parSector(idSector,idCamaronera, codigo ,nombre, descripcion, codigoINP, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion)
		  SELECT DISTINCT
		   @ids + ROW_NUMBER() OVER (ORDER BY SECTOR)
		  ,ID_CAMARONERA
		  ,FORMAT(@ids + ROW_NUMBER() OVER (ORDER BY SECTOR), '00000')
		  ,SECTOR
		  ,SECTOR
		  ,FORMAT(@ids + ROW_NUMBER() OVER (ORDER BY SECTOR), '00000')
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE CAMBIO=2
		  AND NOT EXISTS (SELECT * FROM parSector WHERE nombre = SECTOR)
		  GROUP BY SECTOR, ID_CAMARONERA

		  SELECT @idMaxs = MAX(idSector) FROM parSector
		  IF(@ids =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('Sector',  @idMaxs)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMaxs WHERE tabla ='Sector'
		  END

		  UPDATE x 
		  SET x.COD_SECTOR= y.codigo,
		      x.ID_SECTOR=y.idSector
		  FROM #TMP_AJUSTE_MASIVO x,
		  parSector y
		  WHERE y.nombre = x.SECTOR
		  AND x.CAMBIO=2

	END
	ELSE
	BEGIN
	      UPDATE x 
		  SET x.COD_SECTOR= y.codigo,
		      x.ID_SECTOR=y.idSector
		  FROM #TMP_AJUSTE_MASIVO x,
		  parSector y
		  WHERE y.nombre = x.SECTOR
	END

		      UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parSector x
		  WHERE  NOT EXISTS (SELECT * FROM #TMP_AJUSTE_MASIVO WHERE SECTOR = x.nombre)

	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'parMegaUbicaciones' AND TABLE_SCHEMA = 'dbo')
	BEGIN
		--PRINT 'La tabla parMegaUbicaciones no existe. Creando la tabla...';

		CREATE TABLE parMegaUbicaciones
		(
			NUEVOZONA INT,
			ID_ZONA INT,
			COD_ZONA VARCHAR(10),
			ZONA VARCHAR(80),
			NUEVOCAMARONERA INT,
			ID_CAMARONERA INT,
			COD_CAMARONERA VARCHAR(10),
			CAMARONERA VARCHAR(80),
			ID_SECTOR INT,
			COD_SECTOR VARCHAR(10),
			SECTOR VARCHAR(80),
			CAMBIO INT,
			NUEVOMZONA INT,
			ID_MZONA INT,
			COD_MZONA VARCHAR(10),
			MEGAZONA VARCHAR(80)
		);

		--PRINT 'Tabla parMegaUbicaciones creada exitosamente.';
	END

	INSERT INTO parMegaUbicaciones (
    NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, 
    COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, 
    NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA
	)
	SELECT 
		t.NUEVOZONA, t.ID_ZONA, t.COD_ZONA, t.ZONA, t.NUEVOCAMARONERA, t.ID_CAMARONERA, 
		t.COD_CAMARONERA, t.CAMARONERA, t.ID_SECTOR, t.COD_SECTOR, t.SECTOR, t.CAMBIO, 
		t.NUEVOMZONA, t.ID_MZONA, t.COD_MZONA, t.MEGAZONA
	FROM 
		#TMP_AJUSTE_MASIVO t
	WHERE 
		NOT EXISTS (
			SELECT 1 
			FROM parMegaUbicaciones p 
			WHERE p.ID_ZONA = t.ID_ZONA 
			  AND p.ID_CAMARONERA = t.ID_CAMARONERA
			  AND p.ID_SECTOR = t.ID_SECTOR
			  AND p.ID_MZONA = t.ID_MZONA
		);
	SELECT * FROM #TMP_AJUSTE_MASIVO
	IF NOT OBJECT_ID('tempdb..#TMP_AJUSTE_MASIVO') IS NULL  DROP TABLE #TMP_AJUSTE_MASIVO
	SELECT * FROM parMegaUbicaciones

END TRY 
BEGIN CATCH 
	SELECT ERROR_NUMBER() ERR_NUMERO,ERROR_LINE() ERR_LINEA,ERROR_MESSAGE() ERR_DETALLE;
END CATCH 
GO
