USE IPSPCamaroneraProduccionOswaldito
GO

IF NOT OBJECT_ID('tempdb..#TMP_AJUSTE_MASIVO') IS NULL  DROP TABLE #TMP_AJUSTE_MASIVO
GO 
CREATE TABLE #TMP_AJUSTE_MASIVO
(
    NUEVOZONA INT,
	ID_ZONA INT,
	COD_ZONA VARCHAR(10),
    ZONA VARCHAR(80),
	COD_ZONA_OLD VARCHAR(10),
	NUEVOCAMARONERA INT,
    ID_CAMARONERA INT,
	COD_CAMARONERA VARCHAR(10),
	CAMARONERA VARCHAR(80),
	COD_CAMARONERA_OLD VARCHAR(10),
    ID_SECTOR INT,
	COD_SECTOR VARCHAR(10),
	SECTOR VARCHAR(80),
	CAMBIO INT,
	CODIGO_SECTOR_OLD  VARCHAR(10),
	NUEVOMZONA INT,
	ID_MZONA INT,
	COD_MZONA VARCHAR(10),
    MEGAZONA VARCHAR(80),
  );
SET NOCOUNT off; 

BEGIN TRY 
begin tran
------ MEGA ZONA PENINSULA FALTA ORGANICOCH Y ORGANICOP
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA,	COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',50,'00050','APENDICE',0,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA,	COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',51,'00051','CAMARPASA',0,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',53,'00053','DPESCA',0,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CHANDUY',0,39,'00039','CHANDUY',0,'00000','1B',2,1,0,'00','PENINSULA','','','');

    INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOA',1,0,'00000','PAÑAMAOA',55,'00055','ORGANICOP',1,1,0,'00','PENINSULA','','','');	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOA',1,0,'00000','PAÑAMAOA',56,'00056','PSECTORI',1,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOA',1,0,'00000','PAÑAMAOA',57,'00057','PSECTORII',1,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOA',1,0,'00000','PAÑAMAOA',63,'00063','PSECTORVIII',1,1,0,'00','PENINSULA','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',58,'00058','PSECTORIII',1,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',59,'00059','PSECTORIV',1,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',60,'00060','PSECTORV',1,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',61,'00061','PSECTORVI',1,1,0,'00','PENINSULA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PAÑAMAOB',1,0,'00000','PAÑAMAOB',62,'00062','PSECTORVII',1,1,0,'00','PENINSULA','','','');


-----MEGA ZONA OCEANIA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',71,'00071','ELSALVADOR',0,1,0,'00','OCEANIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',70,'00070','FAROI',0,1,0,'00','OCEANIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',72,'00072','FAROII',0,1,0,'00','OCEANIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',73,'00073','FAROIII',0,1,0,'00','OCEANIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','KOREA',0,43,'00043','KOREA',74,'00074','PANAMA',0,1,0,'00','OCEANIA','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PLAYAS',1,0,'00000','PLAYAS',75,'00075','CABALAI',1,1,0,'00','OCEANIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','PLAYAS',1,0,'00000','PLAYAS',76,'00076','CABALAII',1,1,0,'00','OCEANIA','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','SABANA',1,0,'00000','SABANA',68,'00068','JAMAICA',1,1,0,'00','OCEANIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','SABANA',1,0,'00000','SABANA',69,'00069','SINGAPUR',1,1,0,'00','OCEANIA','','','');


-----MEGA ZONA MEDIA FALTA CORVINERO C -- CUBA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENA',1,0,'00000','BAJENA',24,'00024','ARGENTINA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENA',1,0,'00000','BAJENA',25,'00025','CANADA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENA',1,0,'00000','BAJENA',32,'00032','RUMANIA',1,1,0,'00','MEDIA','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',26,'00026','ESPAÑA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',27,'00027','KANSAS',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',28,'00028','MEXICOI',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',29,'00029','MEXICOII',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',30,'00030','MEXICOIII',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','BAJENB',1,0,'00000','BAJENB',31,'00031','MEXICOIV',1,1,0,'00','MEDIA','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',45,'00045','HONDURASBAJO',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',44,'00044','HONDURASALTO',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',43,'00043','GUATEMALA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',39,'00039','CAPULSA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',42,'00042','FINLANDIA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',40,'00040','COSTARICAI',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROA',1,0,'00000','CORVINEROA',41,'00041','COSTARICAII',1,1,0,'00','MEDIA','','','');
	

    INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROB',1,0,'00000','CORVINEROB',48,'00048','EMIRATOS',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROB',1,0,'00000','CORVINEROB',47,'00047','DAKAR',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CORVINEROB',1,0,'00000','CORVINEROB',46,'00046','CHIPRE',1,1,0,'00','MEDIA','','','');	

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,7,'07','DAULAR',1,0,'00000','DAULAR',38,'00038','TRINIDAD',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,7,'07','DAULAR',1,0,'00000','DAULAR',37,'00037','ARUBA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,7,'07','DAULAR',1,0,'00000','DAULAR',0,'00000','CURAZAO',1,1,0,'00','MEDIA','','','');
	
    INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',23,'00023','RUANDA',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',21,'00021','MARRUECOS',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',82,'00082','EGIPTO',1,1,0,'00','MEDIA','','','');		
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',20,'00020','CAMERUN',1,1,0,'00','MEDIA','','','');	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,3,'03','AFRICA',1,0,'00000','AFRICA',22,'00022','PAKISTAN',1,1,0,'00','MEDIA','','','');
	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',35,'00035','JAPON',1,1,0,'00','MEDIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',33,'00033','CHINA',1,1,0,'00','MEDIA','','','');		
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',34,'00034','HONGKONG',1,1,0,'00','MEDIA','','','');	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,5,'05','ASIA',1,0,'00000','ASIA',77,'00077','VIETNAM',1,1,0,'00','MEDIA','','','');	


	-----MEGA ZONA GOLFO
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','GOLFOA',1,0,'00000','GOLFOA',65,'00065','SUECIAI',1,1,0,'00','GOLFO','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','GOLFOA',1,0,'00000','GOLFOA',66,'00066','SUECIAII',1,1,0,'00','GOLFO','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','GOLFOA',1,0,'00000','GOLFOA',64,'00064','AUSTRALIA',1,1,0,'00','GOLFO','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','GOLFOB',1,0,'00000','GOLFOB',67,'00067','NUEVAZELANDA',1,1,0,'00','GOLFO','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','GOLFOB',1,0,'00000','GOLFOB',83,'00083','BORABORA',1,1,0,'00','GOLFO','','','');


	-----MEGA ZONA TAURA FALTA TAURAA -- TAURAIII TILAPIA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAA',0,1,'00001','TAURAA',79,'00079','TAURAIII',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAA',0,1,'00001','TAURAA',2,'00002','NURACORP',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAA',0,1,'00001','TAURAA',78,'00078','GARITA',0,1,0,'00','TAURA','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',9,'00009','TAURAIV',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',81,'00081','TAURAV',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',10,'00010','TAURAVI',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAB',0,2,'00002','TAURAB',80,'00080','HOLANDA',0,1,0,'00','TAURA','','','');


	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',14,'00014','LALUZ',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',11,'00011','TAURAVII',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',12,'00012','TAURAVIII',0,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAC',0,3,'00003','TAURAC',13,'00013','TAURAIX',0,1,0,'00','TAURA','','','');

	
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAD',1,0,'00000','TAURAD',4,'00004','TAURAI',1,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAD',1,0,'00000','TAURAD',5,'00005','TAURAII',1,1,0,'00','TAURA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','TAURAD',1,0,'00000','TAURAD',3,'00003','PORTILLO',1,1,0,'00','TAURA','','','');



		-----MEGA ZONA CALIFORNIA
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (0,6,'06','CHURUTE',0,25,'00025','CHURUTE',36,'00036','CHURUTE',0,1,0,'00','CALIFORNIA','','','');

	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CALIFORNIAA',1,0,'00000','CALIFORNIAA',49,'00049','LOSANGELES',1,1,0,'00','CALIFORNIA','','','');

    INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',15,'00015','SANTABARBARA',1,1,0,'00','CALIFORNIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',16,'00016','SANDIEGO',1,1,0,'00','CALIFORNIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',17,'00017','SANFRANCISCO',1,1,0,'00','CALIFORNIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',18,'00018','SANTAMONICA',1,1,0,'00','CALIFORNIA','','','');
	INSERT INTO #TMP_AJUSTE_MASIVO(NUEVOZONA, ID_ZONA, COD_ZONA, ZONA, NUEVOCAMARONERA, ID_CAMARONERA, COD_CAMARONERA, CAMARONERA, ID_SECTOR, COD_SECTOR, SECTOR, CAMBIO, NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, COD_ZONA_OLD, COD_CAMARONERA_OLD, CODIGO_SECTOR_OLD) 
	                       VALUES (1,0,'00','CALIFORNIAB',1,0,'00000','CALIFORNIAB',19,'00019','SANTAROSA',1,1,0,'00','CALIFORNIA','','','');
	

		 

		UPDATE x 
		set x.ID_SECTOR=y.idSector
		,x.COD_SECTOR=y.CODSECTOR 
		,x.CODIGO_SECTOR_OLD=y.CODSECTOR 
		,x.COD_ZONA_OLD= y.CODZONA
		,x.COD_CAMARONERA_OLD=y.CODCAMARONERA
		FROM  #TMP_AJUSTE_MASIVO x		     
		INNER JOIN 
		 (SELECT distinct z.idZona, z.codigo AS CODZONA, z.nombre AS ZONA, z.activo AZ,
              c.idCamaronera, c.codigo AS CODCAMARONERA, c.nombre AS CAMARONERA, c.activo AC,
              s.idSector, s.codigo CODSECTOR, s.nombre SECTOR, s.activo ACS
          FROM  parZona z WITH(NOLOCK) 
         INNER JOIN parCamaronera c WITH(NOLOCK) ON
		  c.idZona = z.idZona        
		INNER JOIN parSector  s WITH(NOLOCK) ON
		  s.idCamaronera = c.idCamaronera
		  WHERE s.activo=1) y ON
		y.SECTOR=x.SECTOR



		------generar secuencia basada en id----------------------
		IF NOT OBJECT_ID('tempdb..#zonficacionHomologarCodigo') IS NULL  DROP TABLE #zonficacionHomologarCodigo ;
	
 
		 with BaseCTE as (
		 SELECT  DISTINCT 
		 z.idZona,
		 s.idSector,
		 c.idCamaronera 
		FROM  parZona z WITH(NOLOCK) 
				  inner join parCamaronera c WITH(NOLOCK) ON
				  c.idZona = z.idZona        
				  inner join parSector  s WITH(NOLOCK) ON
				  s.idCamaronera = c.idCamaronera  
				    WHERE s.activo=1
		 )
		 select	
			idZona,
			idSector,
			idCamaronera  ,
			RIGHT('00000' + cast(idCamaronera  as varchar(5)),5) as codigoCamaroneraNew,
			RIGHT('00000' + cast(idSector  as varchar(5)),5) as codigosectorNew
		   into #zonficacionHomologarCodigo
		 FROM 
		  BaseCTE
  



				----TABLA: CAMARONERA
		  UPDATE C SET 
				 C.codigo = MP.codigocamaroneraNew  
		  FROM 
				#zonficacionHomologarCodigo MP INNER JOIN parCamaronera C 
			ON  C.idCamaronera  = MP.idCamaronera
			AND C.idZona        = MP.idZona 

		----TABLA: SECTOR	  
			 UPDATE S SET
				 S.codigo = MP.codigosectorNew  
		  FROM #zonficacionHomologarCodigo MP INNER JOIN parSector S 
			ON S.idSector     = MP.idSector
		   AND S.idCamaronera = MP.idCamaronera

		   --select * from parCamaronera
		   --select * from parSector
------FIN------------

		UPDATE x 
		set x.ID_MZONA=mz.idMegaZona
		,x.COD_MZONA=mz.codigo 
		FROM  #TMP_AJUSTE_MASIVO x
		inner join parMegaZona  mz WITH(NOLOCK) ON
		mz.nombre = x.MEGAZONA 

		UPDATE x 
		set x.ID_ZONA=z.idZona
		,x.COD_ZONA=z.codigo
		FROM  #TMP_AJUSTE_MASIVO x
		inner join parZona z WITH(NOLOCK) ON
		z.nombre=x.ZONA



		UPDATE x 
		set x.ID_CAMARONERA=c.idCamaronera
		,x.COD_CAMARONERA=c.codigo 
		FROM  #TMP_AJUSTE_MASIVO x
		inner join parCamaronera c WITH(NOLOCK) ON
		c.nombre=x.CAMARONERA 

		UPDATE x 
		set x.ID_SECTOR=y.idSector
		,x.COD_SECTOR=y.codigo 	
		FROM  #TMP_AJUSTE_MASIVO x	     
		INNER JOIN 	 parSector y WITH(NOLOCK) ON
		y.nombre=x.SECTOR 
		where y.activo = 1 

	-----megazona
	IF NOT EXISTS(SELECT * FROM parMegaZona WITH(NOLOCK) WHERE nombre IN(SELECT MEGAZONA FROM #TMP_AJUSTE_MASIVO WHERE NUEVOMZONA=1))
	BEGIN
	     DECLARE @idMegaZona int 
		 DECLARE @idMaxMegaZona int 
		 SET @idMegaZona = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WITH(NOLOCK) WHERE tabla='megaZona')
		 BEGIN
			SELECT TOP 1 @idMegaZona = ultimaSecuencia
				FROM parSecuencial WITH(NOLOCK) WHERE tabla='megaZona'
		 END 
		  
		  INSERT INTO parMegaZona(idMegaZona, idDivision, codigo, nombre, descripcion, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion)
		  SELECT DISTINCT
		  @idMegaZona + ROW_NUMBER() OVER (ORDER BY MEGAZONA)
		  ,1
		  ,FORMAT(@idMegaZona + ROW_NUMBER() OVER (ORDER BY MEGAZONA), '00')
		  ,MEGAZONA
		  ,MEGAZONA
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE NUEVOMZONA=1
		  AND NOT EXISTS (SELECT * FROM parMegaZona WITH(NOLOCK) WHERE nombre = MEGAZONA)
		  GROUP BY MEGAZONA

		  SELECT @idMaxMegaZona = MAX(idMegaZona) FROM parMegaZona WITH(NOLOCK)
		  IF(@idMegaZona =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('megaZona',  @idMaxMegaZona)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMaxMegaZona WHERE tabla ='megaZona'
		  END


	END

	      UPDATE x 
		  SET x.COD_MZONA= y.codigo,
		      x.ID_MZONA=y.idMegaZona
		  FROM #TMP_AJUSTE_MASIVO x
		  inner join parMegaZona y WITH(NOLOCK) ON  x.MEGAZONA=y.nombre 

	      UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parMegaZona x WITH(NOLOCK)
		  WHERE  NOT EXISTS (SELECT distinct  MEGAZONA FROM #TMP_AJUSTE_MASIVO WHERE MEGAZONA = x.nombre)
		  AND x.activo=1


	----zona
    IF NOT EXISTS(SELECT * FROM parZona WITH(NOLOCK) WHERE nombre IN(SELECT ZONA FROM #TMP_AJUSTE_MASIVO WHERE NUEVOZONA=1) AND activo=1)
	BEGIN
	     DECLARE @idZona INT 
		 DECLARE @idMaxZona INT 
		 SET @idZona = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WITH(NOLOCK) WHERE tabla='Zona')
		 BEGIN
			SELECT TOP 1 @idZona = ultimaSecuencia
				FROM parSecuencial WITH(NOLOCK) WHERE tabla='Zona'
		 END 
		  
		  INSERT INTO parZona(idZona, idMegaZona, idDivision, codigo, codigoSri ,nombre, descripcion, direccion, telefono, correoElectronico, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion, numeroPedidoLarva, aplicaApiLarvia)
		  SELECT DISTINCT
		  @idZona + ROW_NUMBER() OVER (ORDER BY ZONA)
		  ,ID_MZONA
		  ,1
		  ,FORMAT(@idZona + ROW_NUMBER() OVER (ORDER BY ZONA), '00')
		  ,FORMAT(@idZona + ROW_NUMBER() OVER (ORDER BY ZONA), '000')
		  ,ZONA
		  ,ZONA
		  ,ZONA
		  ,''
		  ,''
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,1
		  ,0
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE NUEVOZONA=1
		  AND NOT EXISTS (SELECT * FROM parZona WITH(NOLOCK) WHERE nombre = ZONA)
		  GROUP BY ZONA,ID_MZONA

		  SELECT @idMaxZona = MAX(idMegaZona) FROM parMegaZona WITH(NOLOCK)
		  IF(@idZona =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('Zona',  @idMaxZona)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMaxZona WHERE tabla ='Zona'
		  END



	END

	      UPDATE x 
		  SET x.COD_ZONA= y.codigo,
		      x.ID_ZONA=y.idZona
		  FROM #TMP_AJUSTE_MASIVO x
		  inner join parZona y WITH(NOLOCK) ON y.nombre = x.ZONA


		UPDATE x 
		  SET x.idMegaZona =  tam.ID_MZONA,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parZona x WITH(NOLOCK)  inner join #TMP_AJUSTE_MASIVO tam on  tam.ZONA =x.nombre AND NUEVOZONA=1

		  UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parZona x WITH(NOLOCK)
		  LEFT JOIN #TMP_AJUSTE_MASIVO tam ON x.nombre = tam.ZONA
		  WHERE tam.ZONA IS NULL
		 AND x.activo = 1;


 
		----camaronera
    IF NOT EXISTS(SELECT * FROM parCamaronera  WITH(NOLOCK) WHERE nombre IN(SELECT CAMARONERA FROM #TMP_AJUSTE_MASIVO WHERE NUEVOCAMARONERA=1) AND activo=1)
	BEGIN
	     DECLARE @id INT 
		 DECLARE @idMax INT 
		 SET @id = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WITH(NOLOCK) WHERE tabla='Camaronera')
		 BEGIN
			SELECT TOP 1 @id = ultimaSecuencia
				FROM parSecuencial WITH(NOLOCK) WHERE tabla='Camaronera'
		 END 
		  
		  INSERT INTO parCamaronera(idCamaronera, idZona, codigo ,nombre, descripcion, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion)
		  SELECT DISTINCT
		   @id + ROW_NUMBER() OVER (ORDER BY CAMARONERA)
		  ,ID_ZONA
		  ,FORMAT(@id + ROW_NUMBER() OVER (ORDER BY CAMARONERA), '00000')
		  ,CAMARONERA
		  ,CAMARONERA
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE NUEVOCAMARONERA=1
		  AND NOT EXISTS (SELECT  *FROM parCamaronera WITH(NOLOCK) WHERE nombre = CAMARONERA  ) --AND idZona=ID_ZONA)
		  GROUP BY CAMARONERA, ID_ZONA

		  SELECT @idMax = MAX(idCamaronera) FROM parCamaronera WITH(NOLOCK)
		  IF(@id =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('Camaronera',  @idMax)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMax WHERE tabla ='Camaronera'
		  END

	END
 

	      UPDATE x 
		  SET x.COD_CAMARONERA= y.codigo,
		      x.ID_CAMARONERA=y.idCamaronera
		  FROM #TMP_AJUSTE_MASIVO x
		  INNER JOIN parCamaronera y WITH(NOLOCK) ON x.CAMARONERA=y.nombre 
		  --WHERE  y.activo=1
		   
		 UPDATE x 
		  SET x.idZona =  Y.ID_ZONA,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parCamaronera x WITH(NOLOCK)
		  inner join #TMP_AJUSTE_MASIVO y on y.CAMARONERA = x.nombre

	SELECT ' finally #TMP_AJUSTE_MASIVO' AS TABLA,* FROM #TMP_AJUSTE_MASIVO
	select '--Camaronera',* from parCamaronera WITH(NOLOCK) where nombre ='KOREA'
	select '--zona',* from parZona WITH(NOLOCK) where  nombre ='KOREA'

		  UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parCamaronera x WITH(NOLOCK)
		  LEFT JOIN #TMP_AJUSTE_MASIVO tam ON x.nombre = tam.CAMARONERA
		  WHERE tam.CAMARONERA IS NULL
		  AND x.activo = 1;


			----sector
    IF NOT EXISTS(SELECT * FROM parSector WITH(NOLOCK) WHERE nombre IN(SELECT SECTOR FROM #TMP_AJUSTE_MASIVO WHERE CAMBIO=2))
	BEGIN
	     DECLARE @ids INT 
		 DECLARE @idMaxs INT 
		 SET @ids = 0
		 IF EXISTS(SELECT  TOP 1 1 FROM parSecuencial WITH(NOLOCK) WHERE tabla='Sector')
		 BEGIN
			SELECT TOP 1 @ids = ultimaSecuencia
				FROM parSecuencial WITH(NOLOCK) WHERE tabla='Sector'
		 END 
		  
		  INSERT INTO parSector(idSector,idCamaronera, codigo ,nombre, descripcion, codigoINP, activo, fechaHoraCreacion, usuarioCreacion, estacionCreacion, fechaHoraModificacion, usuarioModificacion, estacionModificacion)
		  SELECT DISTINCT
		   @ids + ROW_NUMBER() OVER (ORDER BY SECTOR)
		  ,ID_CAMARONERA
		  ,FORMAT(@ids + ROW_NUMBER() OVER (ORDER BY SECTOR), '00000')
		  ,SECTOR
		  ,SECTOR
		  ,FORMAT(@ids + ROW_NUMBER() OVER (ORDER BY SECTOR), '00000')
		  ,1
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  ,GETDATE()
		  ,'adminPsCam'
		  ,''
		  FROM #TMP_AJUSTE_MASIVO
		  WHERE CAMBIO=2
		  AND NOT EXISTS (SELECT distinct nombre FROM parSector WITH(NOLOCK) WHERE nombre = SECTOR)-- AND idCamaronera=ID_CAMARONERA )
		  GROUP BY SECTOR, ID_CAMARONERA

		  SELECT @idMaxs = MAX(idSector) FROM parSector WITH(NOLOCK)
		  IF(@ids =0)
		  BEGIN
		    INSERT INTO parSecuencial VALUES ('Sector',  @idMaxs)  
		  END 
		  ELSE
		  BEGIN
			 UPDATE parSecuencial SET ultimaSecuencia = @idMaxs WHERE tabla ='Sector'
		  END

	END

	      UPDATE x 
		  SET x.COD_SECTOR= y.codigo,
		      x.ID_SECTOR=y.idSector
		  FROM #TMP_AJUSTE_MASIVO x
		  inner join parSector y WITH(NOLOCK) ON  x.SECTOR=y.nombre 
		  where y.activo = 1;


		  UPDATE x 
		  SET x.idCamaronera=  Y.ID_CAMARONERA,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parSector x WITH(NOLOCK)
		  inner join #TMP_AJUSTE_MASIVO y on x.nombre = y.SECTOR
		 WHERE y.CAMBIO IN(1,2)
	 
		  UPDATE x 
		  SET x.activo= 0,
		      x.fechaHoraModificacion=GETDATE(),
			  x.usuarioModificacion='adminPsCam'
		  FROM  parSector x WITH(NOLOCK)
		  LEFT JOIN #TMP_AJUSTE_MASIVO tam ON x.nombre = tam.SECTOR
		  WHERE tam.SECTOR IS NULL
		  AND x.activo = 1;

	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'parMegaUbicaciones' AND TABLE_SCHEMA = 'dbo')
	BEGIN
		--PRINT 'La tabla parMegaUbicaciones no existe. Creando la tabla...';

		CREATE TABLE parMegaUbicaciones
		(
			NUEVOZONA INT,
			ID_ZONA INT,
			COD_ZONA VARCHAR(10),
			COD_ZONA_OLD VARCHAR(10),
			ZONA VARCHAR(80),
			NUEVOCAMARONERA INT,
			ID_CAMARONERA INT,
			COD_CAMARONERA VARCHAR(10),
			COD_CAMARONERA_OLD VARCHAR(10),
			CAMARONERA VARCHAR(80),
			ID_SECTOR INT,
			COD_SECTOR VARCHAR(10),
			COD_SECTOR_OLD VARCHAR(10),
			SECTOR VARCHAR(80),
			CAMBIO INT,
			NUEVOMZONA INT,
			ID_MZONA INT,
			COD_MZONA VARCHAR(10),
			MEGAZONA VARCHAR(80),
			FECHA DATETIME,
		);

		--PRINT 'Tabla parMegaUbicaciones creada exitosamente.';
	END


	INSERT INTO parMegaUbicaciones (
    NUEVOZONA, ID_ZONA, COD_ZONA,  COD_ZONA_OLD,  ZONA, NUEVOCAMARONERA, ID_CAMARONERA, 
    COD_CAMARONERA, COD_CAMARONERA_OLD, CAMARONERA, ID_SECTOR, COD_SECTOR,  COD_SECTOR_OLD, SECTOR, CAMBIO, 
    NUEVOMZONA, ID_MZONA, COD_MZONA, MEGAZONA, FECHA
	)
	SELECT 
		t.NUEVOZONA, t.ID_ZONA, t.COD_ZONA, t.COD_ZONA_OLD, t.ZONA, t.NUEVOCAMARONERA, t.ID_CAMARONERA, 
		t.COD_CAMARONERA, t.COD_CAMARONERA_OLD, t.CAMARONERA, t.ID_SECTOR, t.COD_SECTOR, t.CODIGO_SECTOR_OLD,
		t.SECTOR, t.CAMBIO, 
		t.NUEVOMZONA, t.ID_MZONA, t.COD_MZONA, t.MEGAZONA, GETDATE()
	FROM 
		#TMP_AJUSTE_MASIVO t
	--WHERE 
	--	NOT EXISTS (
	--		SELECT 1 
	--		FROM parMegaUbicaciones p WITH(NOLOCK)
	--		WHERE p.ID_ZONA = t.ID_ZONA 
	--		  AND p.ID_CAMARONERA = t.ID_CAMARONERA
	--		  AND p.ID_SECTOR = t.ID_SECTOR
	--		  AND p.ID_MZONA = t.ID_MZONA
	--);
		
	--SELECT * FROM #TMP_AJUSTE_MASIVO
	IF NOT OBJECT_ID('tempdb..#TMP_AJUSTE_MASIVO') IS NULL  DROP TABLE #TMP_AJUSTE_MASIVO
	SELECT * FROM parMegaUbicaciones WITH(NOLOCK)
	order by SECTOR

	--SELECT * FROM parSector where activo=1
	rollback tran
END TRY 
BEGIN CATCH 
	SELECT ERROR_NUMBER() ERR_NUMERO,ERROR_LINE() ERR_LINEA,ERROR_MESSAGE() ERR_DETALLE;
		rollback tran
END CATCH 
GO
 